// @ts-nocheck
/* eslint-disable */

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async createNote(title: string, content: string) : Promise<Result<Note, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_note", { title, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateNote(id: string, content: string) : Promise<Result<Note, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_note", { id, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteNote(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_note", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listNotes() : Promise<Result<Note[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_notes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getNote(id: string) : Promise<Result<NoteContent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_note", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchNotes(query: string) : Promise<Result<Note[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_notes", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMeetings() : Promise<Result<Meeting[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_meetings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMeeting(id: string) : Promise<Result<Meeting, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_meeting", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startRecording(title: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_recording", { title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopRecording() : Promise<Result<Meeting, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * TODO(spec 0008): orchestrate recorder → transcriber → diarizer
 * → write `transcript.json` → flip `has_transcript`. Left as a
 * deliberate bail! so the IPC surface exists without pretending
 * to work.
 */
async transcribeMeeting(id: string) : Promise<Result<Transcript, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transcribe_meeting", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async summarizeMeeting(id: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("summarize_meeting", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getActiveCalls() : Promise<Result<ActiveCall[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_active_calls") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveAttachment(filename: string, bytes: number[]) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_attachment", { filename, bytes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getConfig() : Promise<Result<AppConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateConfig(config: AppConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Settings (spec 0037) calls this to populate the "Adopt an
 * Obsidian vault" picker. Returns `[]` when Obsidian isn't
 * installed — never an error in that case.
 */
async listObsidianVaults() : Promise<Result<ObsidianVault[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_obsidian_vaults") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns today's daily note (or `date`'s, `YYYY-MM-DD`),
 * creating the file from the default template on first use.
 * Idempotent — the same day always resolves to the same `Note`.
 */
async getOrCreateDailyNote(date: string | null) : Promise<Result<Note, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_or_create_daily_note", { date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Notes that `[[…]]`-link to this one. Match is resolved
 * against the target's current title and filename stem, so
 * renames don't orphan backlinks (spec 0013).
 */
async getBacklinks(id: string) : Promise<Result<Note[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_backlinks", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Wipe the notes index and rebuild it by walking the current
 * vault. Filesystem stays authoritative — the command makes
 * the invariant operational for the "adopt an Obsidian vault"
 * flow (spec 0037) and for disaster recovery when `index.db`
 * is lost (spec 0005 acceptance).
 */
async rebuildFromVault() : Promise<Result<RebuildStats, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rebuild_from_vault") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
callDetected: CallDetected,
recordingProgress: RecordingProgress,
transcriptionProgress: TranscriptionProgress
}>({
callDetected: "call-detected",
recordingProgress: "recording-progress",
transcriptionProgress: "transcription-progress"
})

/** user-defined constants **/



/** user-defined types **/

export type Accelerator = "cpu" | "cuda" | "directml" | "coreml"
export type ActiveCall = { app_name: string; process_name: string; pid: number; is_browser: boolean; detected_at: string }
export type AppConfig = { vault_path: string; 
/**
 * BCP-47 language tag (e.g. "en", "pt-BR"). Empty means "use OS default".
 */
locale?: string; transcriber: TranscriberConfig; diarizer: DiarizerConfig; llm: LlmProvider; autostart: boolean; shortcuts: ShortcutsConfig }
export type CallDetected = { app_name: string; process_name: string }
export type DiarizerConfig = { engine: "none" } | { engine: "pyannote"; segmentation_model: string; embedding_model: string } | { engine: "speakrs"; model_dir: string; accelerator: Accelerator }
export type LlmProvider = { kind: "ollama"; endpoint: string; model: string } | { kind: "claude"; model: string } | { kind: "open_ai"; model: string } | { kind: "groq"; model: string } | { kind: "open_router"; model: string }
export type Meeting = { id: string; title: string; started_at: string; ended_at: string | null; duration_seconds: number | null; participants: string[]; recording_path: string | null; has_transcript: boolean; has_summary: boolean; source_app: string | null }
export type Note = { id: string; title: string; path: string; tags: string[]; created_at: string; updated_at: string }
export type NoteContent = { note: Note; markdown: string }
export type ObsidianVault = { 
/**
 * Stable id Obsidian itself assigns in `obsidian.json` — used
 * only to round-trip selections from the UI.
 */
id: string; 
/**
 * Folder name (leaf of `path`), shown in the Settings list.
 */
name: string; 
/**
 * Absolute filesystem path.
 */
path: string; 
/**
 * Last time Obsidian opened this vault, ms since epoch. `None`
 * when the config has no timestamp — some older installs omit
 * the field.
 */
last_opened_ms: number | null; 
/**
 * Whether `path` actually exists today. A `false` here means
 * Obsidian still lists the vault but the user deleted or moved
 * the folder.
 */
exists: boolean }
export type RebuildStats = { notes_indexed: number; links_indexed: number; 
/**
 * Files the walker found but couldn't index (unreadable, invalid
 * UTF-8, symlink loop). Shown in the UI only when non-zero so
 * the happy path stays quiet.
 */
notes_skipped: number }
export type RecordingProgress = { meeting_id: string; duration_seconds: number; level_db: number }
export type ShortcutsConfig = { new_note: string; open_app: string; agenda: string; meetings: string; toggle_recording: string }
export type TranscriberConfig = 
/**
 * No transcription engine. The app still records audio and
 * stores meetings — transcription commands return an explicit
 * "engine not configured" error. This is the default for fresh
 * installs so the app boots without a model on disk.
 */
{ engine: "none" } | { engine: "whisper"; model_path: string; accelerator: Accelerator } | { engine: "parakeet"; model_dir: string; accelerator: Accelerator }
export type Transcript = { meeting_id: string; language: string | null; segments: TranscriptSegment[] }
export type TranscriptSegment = { start: number; end: number; text: string; speaker: string | null; confidence: number | null }
export type TranscriptionProgress = { meeting_id: string; percent: number; message: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
